trigger:
  batch: False
  branches:
    include:
      - '*'
pr:
  branches:
    include:
      - '*'

jobs:
- job:
  displayName: Windows
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
      Python38:
        python.version: '3.8'

  steps:
  - script: |
      call "%CONDA%\Scripts\activate" base
      echo "##vso[task.setvariable variable=PATH]%CONDA%\Scripts;%PATH%"
    displayName: Add conda to PATH and activate conda base
  - script: conda install python=%PYTHON_VERSION% ipython numpy seaborn statsmodels matplotlib sphinx pillow pytest pytest-cov sphinx_rtd_theme joblib plotly
    displayName: Setup conda environment
  - script: python setup.py develop
    displayName: Install sphinx-gallery
  - script: pytest --tb=short sphinx_gallery
    displayName: pytest
  - script: |
      cd doc
      sphinx-build -D plot_gallery=0 -b html -d _build\doctrees . _build\html
    displayName: make html-noplot
  - bash: |
      cd doc
      make clean
    displayName: make clean
  - script: |
      cd doc
      sphinx-build -b html -d _build\doctrees . _build\html
    displayName: make html
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: 'junit-*.xml'
      testRunTitle: 'Publish test results for $(Agent.JobName) $(TEST_MODE) $(PYTHON_VERSION)'
      failTaskOnFailedTests: true
    condition: succeededOrFailed()
