from argparse import ArgumentParser
import os.path
import shutil
import subprocess
import sys


def main():
    parser = ArgumentParser(
        description=
        "Clean intermediate files generated by sphinx-gallery, and call "
        "'python -msphinx -M clean' with the same arguments.")
    parser.add_argument("sourcedir")
    parser.add_argument("builddir")
    args, _ = parser.parse_known_args()
    d = {}
    with open(os.path.join(args.sourcedir, "conf.py")) as file:
        exec(file.read(), d)
    sg_conf = d["sphinx_gallery_conf"]
    for path in sg_conf["gallery_dirs"]:
        shutil.rmtree(os.path.join(args.sourcedir, path), ignore_errors=True)
    shutil.rmtree(os.path.join(args.sourcedir, sg_conf["backreferences_dir"]),
                  ignore_errors=True)
    subprocess.check_call(
        [sys.executable, "-msphinx", "-M", "clean"] + sys.argv[1:])


if __name__ == "__main__":
    main()
