from argparse import ArgumentParser
import shutil


def main():
    parser = ArgumentParser(
        description=
        "Clean all intermediate files generated by sphinx-gallery.")
    parser.parse_args()
    d = {}
    with open("conf.py") as file:
        exec(file.read(), d)
    sg_conf = d["sphinx_gallery_conf"]
    for path in sg_conf["gallery_dirs"]:
        shutil.rmtree(path, ignore_errors=True)
    shutil.rmtree(sg_conf["backreferences_dir"], ignore_errors=True)


if __name__ == "__main__":
    main()
